You are a content scheduling expert. Given below are the list of article ideas accepted for publishing.

{{accepted_articles_idea}}

I want to have {{no_of_articles}} published every week. Today is {{current_date}}.
Give me a proposed schedule for the publication of each article.

Generate a JSON list of objects with two columns - the first column is Publication Date and the other column in Article Title.
For the JSON list, use the keys publication_date and article_title. Ensure the list includes all of the accepted ideas
for the titles. It must be a complete list. DO NOT SKIP ANY TITLES IN YOUR REPONSE UNDER NO CIRCUMSTANCES.

